version: "3"

env:
  COMPILER: /usr/bin/clang++
  DEBUG_FLAGS: -g -Wall -fsanitize=address

tasks:
  default:
    - task: build-debug
    - task: run

  build-debug:
    cmds:
      - cmake -S . -B build -DCMAKE_CXX_COMPILER="${COMPILER}" -DCMAKE_CXX_FLAGS="${DEBUG_FLAGS}"
      - cmake --build build

  build:
    cmds:
      - cmake -S . -B build -DCMAKE_CXX_COMPILER="${COMPILER}" -DCMAKE_CXX_FLAGS="-O3"
      - cmake --build build

  run:
    cmds:
      - ./build/rb-tree-test.out

  run-valgrind:
    cmds:
      - valgrind --leak-check=full --show-leak-kinds=all ./build/rb-tree-test.out

  run-gdb:
    cmds:
      - gdb ./build/rb-tree-test.out
